AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'


Globals:
  Function:
    Timeout: 120
    Runtime: nodejs10.x
    MemorySize: 256

Resources: 
  FederationFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  FederationFunctionExecutionPolicy:
    Type: AWS::IAM::Policy
    DependsOn: FederationFunctionExecutionRole
    Properties:
      PolicyName: !Sub ${AWS::StackName}-exec-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "logs:*"
              - "events:*"
              - "dynamodb:*"
              - "sns:*"
            Resource: "*"
      Roles:
        - !Ref FederationFunctionExecutionRole

  FederationFunction:
    Type: AWS::Serverless::Function
    DependsOn: FederationFunctionExecutionRole
    Properties:
      Handler: lib/graphql.handler
      Events:
        Request:
          Type: Api
          Properties:
            Path: {proxy+}
            Method: ANY
  
  HelloFunction:
    Type: AWS::Serverless::Function
    DependsOn: FederationFunctionExecutionRole
    Properties:
      Handler: lib/hello.handler
      Events:
        Request:
          Type: Api
          Properties:
            Path: /hello
            Method: ANY

  GoodbyeFunction:
    Type: AWS::Serverless::Function
    DependsOn: FederationFunctionExecutionRole
    Properties:
      Handler: lib/goodbye.handler
      Events:
        Request:
          Type: Api
          Properties:
            Path: /goodbye
            Method: ANY
    
    
    