AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'


Globals:
  Function:
    Timeout: 120
    Runtime: nodejs10.x
    MemorySize: 256

Resources: 
  FederationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lib/graphql.handler
      Events:
        Request:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY